datasource:
#   default: ${APP_ENV}
#   development:
#     username: ""
#     password: ""
#     url: "jdbc:h2:~/test"
  db:
#     production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true

