#datasource:
#  db:
#    username: rusglagol
#    password: Polk_8814
#    url: jdbc:postgresql://localhost:5432/url

ebean:
  migration:
    run: true
datasource:
  db:
    username: sa
    password: sa
    #url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:test_db

#ebean:
#  migration:
#    run: true
#datasource:
#  default: ${APP_ENV}
#  development:
#    username: sa
#    password: sa
#    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE
#  production:
#    username: rusglagol
#    password: Polk_8814
#    url: jdbc:postgresql://localhost:5432/url

