# datasource:
#   default: ${APP_ENV}
#   development:
#     username: ""
#     password: ""
#     url: "jdbc:h2:~/test"
#   production:
#     username: ${PGUSER}
#     password: ${PGPASSWORD}
#     url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

# ebean:
#   development:
#     migration:
#       run: true
#   production:
#     migration:
#       run: true
      
datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: jdbc:h2:mem:dev_db
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  migration:
    run: true
