# datasource:
#   default: ${APP_ENV}
#   development:
#     username: ""
#     password: ""
#     url: "jdbc:h2:~/test"
#   production:
#     username: ${PGUSER}
#     password: ${PGPASSWORD}
#     url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

# ebean:
#   development:
#     migration:
#       run: true
#   production:
#     migration:
#       run: true
      
datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:~/test"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
ebean:
  ddl:
    run: true
    generate: true
    seedSql: seed.sql
  migration:
    run: true

# ebean:
#   development:
#     migration:
#       run: true
#   production:
#     migration:
#       run: true
