datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:file:~/h2/java-project-72"
  production:
    username: rusglagol
    password: Polk_8814
    url: "jdbc:postgresql://localhost/url"